services:
  KayStrobach\Themes\TsConfig\Loader:
    public: true
    tags:
      - name: event.listener
        identifier: 'add-site-configuration'
        event: TYPO3\CMS\Core\Configuration\Event\ModifyLoadedPageTsConfigEvent